import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Button } from "@mui/material";
import { useRouter } from "next/router";
import { MarginTwoTone, Padding } from "@mui/icons-material";
import Homebar from "@/components/Homebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homebar/>
      <Box sx={{ padding: "2%",marginTop:{lg:"2%",xs:"30%"},justifyContent:"center",textAlign:"center" }}>
        <img src="./images/intro.png" style={{ width: "90vw", height: "auto" }} />
        <h4>
          "Efficiently organize tasks, boost productivity, and streamline teamwork with our intuitive task manager website."
        </h4><br/>
        <center><Button variant="outlined" onClick={(e)=>router.push('/add')}>Start</Button></center>
      </Box>
    </>
  );
}
