version: '3'

services:
  web:
    depends_on:
      - server
    build: 
      context: ./frontend/taskmanager
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./frontend/taskmanager/package.json
          action: rebuild
        - path: ./frontend/taskmanager/next.config.js
          action: rebuild
        - path: ./frontend/taskmanager/package-lock.json
          action: rebuild
        - path: ./frontend/taskmanager
          target: /usr/app/taskmanager
          action: sync    

  server:
    build: 
      context: ./server
    ports:
      - "3001:3001"  
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /usr/app/server 
          action: sync+restart   

volumes:
  Docker:
